### ISSUE TITLE
Dangle Errors

### ISSUE THREAD

**Issue by brigsz** [agrc/Spillman#3]
AGRC needs a way to find deadend and cul de sac street features that are responsible for creating dangle errors in a geodatabase topology and mark them as exceptions.  The area within the buffer distance of each error is searched for street features.  If only one street feature is found, the error is likely a legitimate dead end and the feature is marked as an exception.

This script must be run in an edit session in ArcMap on a validated topology with  a "no dangles" topology rule defined.  The buffer distance should be 10 meters.  At the moment this must run on 10.1 as a start and 10.3.1 for others.

**Comment by steveoh** [comment]
The code process would then be, 

From the topology results marked as errors (how are they marked as errors):
- buffer something by 10 meters, is it a point or a line?
- Use that geometry or geometries created to spatially query the roads data set
- If the intersection geometry count is less than 2 update the table to somehow reflect the "dangle" is legitimate. 

Are you able to fill in the unknown pieces @brigsz? 

On the surface this seems like a day or two. I think there may be other issues that haven't surfaced here so I would guess work could be required for a week. For example, can arcpy access the topology results and how are the errors marked as exceptions. Using arcobjects will likely require more effort.

**Comment by brigsz** [comment]
ArcMap seems to have defaults as to how a dangle is shown.  I have included an image of that

![dangleshot](https://cloud.githubusercontent.com/assets/6306463/12403491/6003d3d2-bdf1-11e5-984d-d86f7f6c234f.png)

**Comment by brigsz** [comment]
yah, I need to learn how to get the crop tool functional

**Comment by brigsz** [comment]
I wonder if the answer lies in the GeodatabaseTopologyException class

**Comment by brigsz** [comment]
I am closing this one as I barely remember it.  I suspect I was processing data and was trying to figure out a way to narrow  the selection to get to what I was looking for
